spring:
  activiti:
    check-process-definitions: false
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
security:
  basic:
    enabled: false